# Circus MCP Manager Configuration - 新しいアーキテクチャ設定

# MCP Server Configuration
mcp:
  server_name: "circus-mcp-manager"
  version: "2.0.0"
  protocol_version: "2024-11-05"

  # Capabilities
  capabilities:
    tools: true
    resources: true
    prompts: false
    logging: true

# Circus Configuration
circus:
  endpoint: "tcp://127.0.0.1:5555"
  timeout: 30
  connection_retries: 3
  retry_delay: 1.0

# Logging Configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

  # Background processing
  background_processing:
    enabled: true
    queue_size: 1000
    batch_size: 100
    processing_interval: 1.0

  # Log retention
  retention:
    max_entries_per_process: 10000
    cleanup_interval: 3600 # seconds

  # Alert configuration
  alerts:
    enabled: true
    error_threshold: 10 # errors per minute
    critical_immediate: true

# Repository Configuration
repositories:
  # Default repository type: memory, file, database
  default_type: "memory"

  # File-based repository settings
  file:
    base_path: "./data"
    processes_file: "processes.json"
    logs_file: "logs.json"
    backup_enabled: true
    backup_interval: 3600

  # Database repository settings (future)
  database:
    type: "sqlite"
    connection_string: "sqlite:///circus_mcp.db"
    pool_size: 5

# Performance Configuration
performance:
  # Process management
  process_operations:
    timeout: 30
    concurrent_limit: 10

  # Log processing
  log_processing:
    max_concurrent_parsers: 5
    buffer_size: 1000
    flush_interval: 5.0

  # Memory management
  memory:
    max_log_entries: 50000
    cleanup_threshold: 0.8
    gc_interval: 300

# Security Configuration
security:
  # Process restrictions
  allowed_commands:
    - "python"
    - "node"
    - "java"
    - "gunicorn"
    - "uwsgi"

  # Path restrictions
  allowed_paths:
    - "/app"
    - "/opt/app"
    - "/home/app"

  # Resource limits
  resource_limits:
    max_processes_per_watcher: 10
    max_memory_per_process: "1GB"
    max_cpu_per_process: 2.0

# Development Configuration
development:
  debug: false
  mock_circus: false
  test_mode: false

  # Testing
  testing:
    mock_data_enabled: false
    test_processes:
      - name: "test-webapp"
        command: "python -m http.server 8000"
        working_dir: "/tmp"
